version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - GIT_REPO_URL=${GIT_REPO_URL}
        - APP_TARGET=${APP_TARGET}
    container_name: node_app
    ports:
      - ${APP_PORT}:${APP_PORT}

